[package]
name = "basic-rust-evm-fuzzer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.11.1", features = ["full", "node-bindings"] }
eyre = "0.6.12"
serde_json = "1.0.139"
tokio = "1.43.0"
rand = "0.8"
